## Dataset Summary Report

This report aims to provide a comprehensive overview of the dataset's structure and characteristics using Python and the Pandas library.

In [1]:
import pandas as pd

# Load the CSV dataset into a Pandas DataFrame
df = pd.read_csv('Day7_Student_Dataset.csv')

print("Dataset 'Day7_Student_Dataset.csv' loaded successfully.")

Dataset 'Day7_Student_Dataset.csv' loaded successfully.

### 1. Inspecting the Dataset

Let's start by looking at the first and last few rows to get a sense of the data structure and content.

In [2]:
print("First 5 rows:")
display(df.head())

print("\nLast 5 rows:")
display(df.tail())

First 5 rows:

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
4,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow

Last 5 rows:

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
20,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
21,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
23,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

### 2. Viewing Random Samples

Random samples can help in understanding the diversity of data entries.

In [3]:
print("5 random rows from the dataset:")
display(df.sample(5))

5 random rows from the dataset:

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
5,1006,Ishita Gupta,20,Computer Science,88.0,93.0,Bengaluru
11,1012,Aisha Mir,19,Computer Science,68.0,72.0,Delhi
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
18,1019,Yusuf Dar,20,Data Science,NaN,87.0,Srinagar

### 3. Dataset Shape, Columns, and Index

Understanding the dimensions and identifiers of the dataset.

In [4]:
print(f"Dataset shape (rows, columns): {df.shape}")
print(f"Number of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")

print("\nColumn names:")
display(df.columns.tolist())

print("\nDataset index:")
display(df.index)

Dataset shape (rows, columns): (25, 7)
Number of rows: 25
Number of columns: 7

Column names:

['Student_ID',
 'Name',
 'Age',
 'Course',
 'Marks',
 'Attendance_Percentage',
 'City']

Dataset index:

RangeIndex(start=0, stop=25, step=1)

### 4. Data Types and Non-Null Counts (using `info()`)

The `info()` method provides a concise summary of the DataFrame, including data types, non-null values, and memory usage. It's excellent for quickly identifying missing values and incorrect data types.

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             25 non-null     int64
 1   Name                   25 non-null     object
 2   Age                    25 non-null     int64
 3   Course                 25 non-null     object
 4   Marks                  24 non-null     float64
 5   Attendance_Percentage  24 non-null     float64
 6   City                   24 non-null     object
dtypes: float64(2), int64(2), object(3)
memory usage: 1.5+ KB

### 5. Descriptive Statistics (using `describe()`)

The `describe()` method generates descriptive statistics that summarize the central tendency, dispersion, and shape of a dataset's distribution, excluding `NaN` values.

In [6]:
print("Descriptive statistics for numerical columns:")
display(df.describe())

print("\nDescriptive statistics for all columns (including categorical):")
display(df.describe(include='all'))

Descriptive statistics for numerical columns:

        Student_ID        Age      Marks  Attendance_Percentage
count    25.000000  25.000000  24.000000              24.000000
mean   1013.000000  20.000000  82.250000              87.083333
std       7.359801   1.414214   8.689074               7.252686
min    1001.000000  18.000000  68.000000              72.000000
25%    1007.000000  19.000000  75.500000              82.750000
50%    1013.000000  20.000000  82.500000              88.000000
75%    1019.000000  21.000000  89.250000              92.250000
max    1025.000000  23.000000  96.000000              98.000000

Descriptive statistics for all columns (including categorical):

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
count,25.000000,25,25.000000,25,24.000000,24.000000,24
unique,NaN,25,NaN,3,NaN,NaN,13
top,NaN,Aarav Sharma,NaN,Data Science,NaN,NaN,Srinagar
freq,NaN,1,NaN,9,NaN,NaN,6
mean,1013.000000,NaN,20.000000,NaN,82.250000,87.083333,NaN
std,7.359801,NaN,1.414214,NaN,8.689074,7.252686,NaN
min,1001.000000,NaN,18.000000,NaN,68.000000,72.000000,NaN
25%,1007.000000,NaN,19.000000,NaN,75.500000,82.750000,NaN
50%,1013.000000,NaN,20.000000,NaN,82.500000,88.000000,NaN
75%,1019.000000,NaN,21.000000,NaN,89.250000,92.250000,NaN
max,1025.000000,NaN,23.000000,NaN,96.000000,98.000000,NaN

### 6. Basic Observations about the Dataset

Based on the above analysis, here are some key observations:

*   **Number of Rows and Columns:** The dataset contains `25` rows and `7` columns.
*   **Available Features:** The features (columns) are `Student_ID`, `Name`, `Age`, `Course`, `Marks`, `Attendance_Percentage`, and `City`.
*   **Data Types:**
    *   `Student_ID`, `Age`: Integer (`int64`)
    *   `Marks`, `Attendance_Percentage`: Float (`float64`)
    *   `Name`, `Course`, `City`: Object (`object`), which typically means strings.
*   **Missing Values:**
    *   `Marks` column has 24 non-null entries out of 25, indicating **1 missing value**.
    *   `Attendance_Percentage` column has 24 non-null entries out of 25, indicating **1 missing value**.
    *   `City` column has 24 non-null entries out of 25, indicating **1 missing value**.
    *   `Student_ID`, `Name`, `Age`, and `Course` columns have no missing values.