In [1]:
import pandas as pd

# Load the dataset
file_path = '/content/Day11_Messy_Company_Employee_Dataset.csv'
df = pd.read_csv(file_path)

print('Dataset loaded successfully. Here are the first 5 rows:')
display(df.head())

Dataset loaded successfully. Here are the first 5 rows:

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,NaN,Data Scientist,48.0,Other,108371.0,13.2,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.1,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.2,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,NaN,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.9,2018-07-24,Hyderabad,4.0,Hybrid

In [2]:
print('\nDataset Information:')
df.info()

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        157 non-null    object
 1   Employee_Name      157 non-null    object
 2   Department         152 non-null    object
 3   Job_Title          157 non-null    object
 4   Age                153 non-null    float64
 5   Gender             152 non-null    object
 6   Annual_Salary      152 non-null    float64
 7   Experience_Years   154 non-null    float64
 8   Joining_Date       157 non-null    object
 9   City               152 non-null    object
 10  Performance_Score  154 non-null    float64
 11  Work_Mode          155 non-null    object
dtypes: float64(4), object(8)
memory usage: 14.8+ KB

In [3]:
print('\nDescriptive Statistics:')
display(df.describe(include='all'))

Descriptive Statistics:

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
count,157,157,152,157,153.000000,152,152.000000,154.000000,157,152,154.000000,155
unique,150,130,10,23,NaN,5,NaN,NaN,147,13,NaN,5
top,EMP0075,Nikhil Das,Marketing,Data Scientist,NaN,Male,NaN,NaN,2025-08-17,Chandigarh,NaN,Remote
freq,2,3,23,13,NaN,75,NaN,NaN,2,24,NaN,56
mean,NaN,NaN,NaN,NaN,38.130719,NaN,89240.592105,8.990909,NaN,NaN,3.525974,NaN
std,NaN,NaN,NaN,NaN,9.361661,NaN,22626.172309,4.983874,NaN,NaN,0.930233,NaN
min,NaN,NaN,NaN,NaN,21.000000,NaN,43331.000000,0.600000,NaN,NaN,2.000000,NaN
25%,NaN,NaN,NaN,NaN,30.000000,NaN,71198.500000,4.450000,NaN,NaN,3.000000,NaN
50%,NaN,NaN,NaN,NaN,39.000000,NaN,90046.500000,9.350000,NaN,NaN,4.000000,NaN
75%,NaN,NaN,NaN,NaN,46.000000,NaN,107328.000000,13.200000,NaN,NaN,4.000000,NaN
max,NaN,NaN,NaN,NaN,52.000000,NaN,162942.000000,17.400000,NaN,NaN,5.000000,NaN

In [4]:
# Drop duplicate Employee_ID entries, keeping the first occurrence
df.drop_duplicates(subset='Employee_ID', keep='first', inplace=True)
print('Duplicate Employee_IDs removed. New number of rows:', len(df))

Duplicate Employee_IDs removed. New number of rows: 150

In [5]:
# Standardize 'Work_Mode' column
df['Work_Mode'] = df['Work_Mode'].replace({'In-office': 'Office', 'Work From Home': 'Remote'})
print('\nWork_Mode values after standardization:')
print(df['Work_Mode'].value_counts(dropna=False))

Work_Mode values after standardization:
Work_Mode
Remote    54
Hybrid    48
Office    44
NaN        2
REMOTE     1
remote     1
Name: count, dtype: int64

In [6]:
# Further standardize 'Work_Mode' by converting to consistent case (e.g., capitalize first letter)
df['Work_Mode'] = df['Work_Mode'].str.capitalize()
print('\nWork_Mode values after complete standardization:')
print(df['Work_Mode'].value_counts(dropna=False))

Work_Mode values after complete standardization:
Work_Mode
Remote    56
Hybrid    48
Office    44
NaN        2
Name: count, dtype: int64

In [7]:
# Standardize 'Department' column
# Check unique values first to identify inconsistencies
print('\nUnique values for Department before standardization:')
print(df['Department'].unique())

# Assuming 'Data Science' and 'Research' might be intended to be distinct, but let's check further if any overlaps.
# For now, let's just make sure they are consistently cased if needed, or replace common misspellings.
# As per initial observation, 'Data Science' and 'Research' are distinct. Let's make sure all are capitalized.
df['Department'] = df['Department'].str.capitalize()
print('\nDepartment values after standardization (capitalize):')
print(df['Department'].value_counts(dropna=False))

Unique values for Department before standardization:
[nan 'Marketing' 'Human Resources' 'Engineering' 'Sales' 'Finance'
 'Data & Analytics' 'Customer Success' 'Operations' 'ENGINEERING'
 'engineering']

Department values after standardization (capitalize):
Department
Engineering         23
Marketing           22
Customer success    20
Sales               18
Human resources     16
Operations          16
Data & analytics    15
Finance             15
NaN                  5
Name: count, dtype: int64

In [8]:
# Quantify missing values again after initial cleaning steps
print('\nMissing values after removing duplicates and standardizing Work_Mode/Department:')
display(df.isnull().sum())

Missing values after removing duplicates and standardizing Work_Mode/Department:

Employee_ID          0
Employee_Name        0
Department           5
Job_Title            0
Age                  4
Gender               5
Annual_Salary        4
Experience_Years     3
Joining_Date         0
City                 5
Performance_Score    3
Work_Mode            2
dtype: int64

In [12]:
# Further standardize 'Department' to handle 'Customer Success' correctly
df['Department'] = df['Department'].replace('Customer success', 'Customer Success')
print('\nDepartment values after further standardization:')
print(df['Department'].value_counts(dropna=False))

Department values after further standardization:
Department
Engineering         28
Marketing           22
Customer Success    20
Sales               18
Human resources     16
Operations          16
Data & analytics    15
Finance             15
Name: count, dtype: int64

In [13]:
# Impute missing values

# Categorical columns: impute with mode
for col in ['Department', 'Gender', 'City', 'Work_Mode']:
    mode_val = df[col].mode()[0]
    df[col].fillna(mode_val, inplace=True)
    print(f'Missing values in {col} imputed with mode: {mode_val}')

# Numerical columns: impute with median
for col in ['Age', 'Annual_Salary', 'Experience_Years', 'Performance_Score']:
    median_val = df[col].median()
    df[col].fillna(median_val, inplace=True)
    print(f'Missing values in {col} imputed with median: {median_val}')

print('\nMissing values after imputation:')
display(df.isnull().sum())

Missing values in Department imputed with mode: Engineering
Missing values in Gender imputed with mode: Male
Missing values in City imputed with mode: Pune
Missing values in Work_Mode imputed with mode: Remote
Missing values in Age imputed with median: 39.0
Missing values in Annual_Salary imputed with median: 89302.0
Missing values in Experience_Years imputed with median: 9.2
Missing values in Performance_Score imputed with median: 4.0

Missing values after imputation:

/tmp/ipykernel_2246/622046317.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(mode_val, inplace=True)
/tmp/ipykernel_2246/622046317.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(median_val, inplace=True)

Employee_ID          0
Employee_Name        0
Department           0
Job_Title            0
Age                  0
Gender               0
Annual_Salary        0
Experience_Years     0
Joining_Date         0
City                 0
Performance_Score    0
Work_Mode            0
dtype: int64

In [14]:
# Convert 'Joining_Date' to datetime objects and verify data types
df['Joining_Date'] = pd.to_datetime(df['Joining_Date'], errors='coerce')

print('\nData types after conversion:')
df.info()

Data types after conversion:
<class 'pandas.core.frame.DataFrame'>
Index: 150 entries, 0 to 155
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        150 non-null    object
 1   Employee_Name      150 non-null    object
 2   Department         150 non-null    object
 3   Job_Title          150 non-null    object
 4   Age                150 non-null    float64
 5   Gender             150 non-null    object
 6   Annual_Salary      150 non-null    float64
 7   Experience_Years   150 non-null    float64
 8   Joining_Date       150 non-null    datetime64[ns]
 9   City               150 non-null    object
 10  Performance_Score  150 non-null    float64
 11  Work_Mode          150 non-null    object
dtypes: datetime64[ns](1), float64(4), object(7)
memory usage: 15.2+ KB

In [15]:
# Final verification of the dataset after cleaning
print('\nFinal check of missing values:')
display(df.isnull().sum())

print('\nFinal check of data types:')
df.info()

print('\nFirst 5 rows of the cleaned dataset:')
display(df.head())

Final check of missing values:

Employee_ID          0
Employee_Name        0
Department           0
Job_Title            0
Age                  0
Gender               0
Annual_Salary        0
Experience_Years     0
Joining_Date         0
City                 0
Performance_Score    0
Work_Mode            0
dtype: int64

Final check of data types:
<class 'pandas.core.frame.DataFrame'>
Index: 150 entries, 0 to 155
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        150 non-null    object
 1   Employee_Name      150 non-null    object
 2   Department         150 non-null    object
 3   Job_Title          150 non-null    object
 4   Age                150 non-null    float64
 5   Gender             150 non-null    object
 6   Annual_Salary      150 non-null    float64
 7   Experience_Years   150 non-null    float64
 8   Joining_Date       150 non-null    datetime64[ns]
 9   City               150 non-null    object
 10  Performance_Score  150 non-null    float64
 11  Work_Mode          150 non-null    object
dtypes: datetime64[ns](1), float64(4), object(7)
memory usage: 15.2+ KB

First 5 rows of the cleaned dataset:

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,Engineering,Data Scientist,48.0,Other,108371.0,13.2,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.1,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human resources,HR Manager,28.0,Female,119400.0,13.2,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,9.2,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.9,2018-07-24,Hyderabad,4.0,Hybrid

In [16]:
# Export the cleaned dataset to a new CSV file
output_file_path = '/content/Cleaned_Company_Employee_Dataset.csv'
df.to_csv(output_file_path, index=False)
print(f'\nCleaned dataset exported to {output_file_path}')

Cleaned dataset exported to /content/Cleaned_Company_Employee_Dataset.csv

In [9]:
# Further standardize 'Department' to handle 'Customer Success' correctly
df['Department'] = df['Department'].replace('Customer success', 'Customer Success')
print('\nDepartment values after further standardization:')
print(df['Department'].value_counts(dropna=False))

Department values after further standardization:
Department
Engineering         23
Marketing           22
Customer Success    20
Sales               18
Human resources     16
Operations          16
Data & analytics    15
Finance             15
NaN                  5
Name: count, dtype: int64

In [10]:
# Impute missing values

# Categorical columns: impute with mode
for col in ['Department', 'Gender', 'City', 'Work_Mode']:
    mode_val = df[col].mode()[0]
    df[col].fillna(mode_val, inplace=True)
    print(f'Missing values in {col} imputed with mode: {mode_val}')

# Numerical columns: impute with median
for col in ['Age', 'Annual_Salary', 'Experience_Years', 'Performance_Score']:
    median_val = df[col].median()
    df[col].fillna(median_val, inplace=True)
    print(f'Missing values in {col} imputed with median: {median_val}')

print('\nMissing values after imputation:')
display(df.isnull().sum())

Missing values in Department imputed with mode: Engineering
Missing values in Gender imputed with mode: Male
Missing values in City imputed with mode: Pune
Missing values in Work_Mode imputed with mode: Remote
Missing values in Age imputed with median: 39.0
Missing values in Annual_Salary imputed with median: 89302.0
Missing values in Experience_Years imputed with median: 9.2
Missing values in Performance_Score imputed with median: 4.0

Missing values after imputation:

/tmp/ipykernel_2246/622046317.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(mode_val, inplace=True)
/tmp/ipykernel_2246/622046317.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(median_val, inplace=True)

Employee_ID          0
Employee_Name        0
Department           0
Job_Title            0
Age                  0
Gender               0
Annual_Salary        0
Experience_Years     0
Joining_Date         0
City                 0
Performance_Score    0
Work_Mode            0
dtype: int64

In [11]:
# Convert 'Joining_Date' to datetime objects and verify data types
df['Joining_Date'] = pd.to_datetime(df['Joining_Date'], errors='coerce')

print('\nData types after conversion:')
df.info()

Data types after conversion:
<class 'pandas.core.frame.DataFrame'>
Index: 150 entries, 0 to 155
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        150 non-null    object
 1   Employee_Name      150 non-null    object
 2   Department         150 non-null    object
 3   Job_Title          150 non-null    object
 4   Age                150 non-null    float64
 5   Gender             150 non-null    object
 6   Annual_Salary      150 non-null    float64
 7   Experience_Years   150 non-null    float64
 8   Joining_Date       150 non-null    datetime64[ns]
 9   City               150 non-null    object
 10  Performance_Score  150 non-null    float64
 11  Work_Mode          150 non-null    object
dtypes: datetime64[ns](1), float64(4), object(7)
memory usage: 15.2+ KB